env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "amd64"

archives:
  -
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'